version: "3"
services:
  cronicle:
      build: ./
      image:  dalongrong/cronicle
      ports:
      - "3012:3012"
  cronicle2:
      build: ./
      hostname: cronicle2
      image:  dalongrong/cronicle
      ports:
      - "3013:3012"
  cronicle3:
      build: ./
      hostname: cronicle3
      image:  dalongrong/cronicle
      ports:
      - "3014:3012"